language: node_js
env:
  CI: true

node_js:
  - 10

cache: false

install:
  - npm i -g lerna
  - npm install
  - npm run install:packages
script: npm run test:all:cli
notifications:
  email: melihkorkmaz84@gmail.com
